CoD.ReaperHUD = {}
CoD.ReaperHUD.new = function ( f1_arg0 )
	local f1_local0 = CoD.AirVehicleHUD.new( "reaper", f1_arg0, 0, 1, 0, "digital_noise_filter_remote_mortar" )
	f1_local0:addIRToggle()
	f1_local0:addCrosshairDistance( "LAS" )
	f1_local0:addFakeHighAuto()
	f1_local0:addRecBox()
	f1_local0:addSignalBox()
	CoD.ReaperHUD.AddReticle( f1_local0 )
	return f1_local0
end

CoD.ReaperHUD.AddReticle = function ( f2_arg0 )
	local self = LUI.UIImage.new()
	self:setLeftRight( false, false, -128, 128 )
	self:setTopBottom( false, false, -128, 128 )
	self:setRGB( f2_arg0.colorR, f2_arg0.colorG, f2_arg0.colorB )
	self:setImage( RegisterMaterial( "mp_hud_reaper_reticle" ) )
	f2_arg0:addElement( self )
	local f2_local1 = LUI.UIElement.new()
	f2_local1:setLeftRight( false, false, -234, 234 )
	f2_local1:setTopBottom( true, false, 50, 114 )
	f2_local1:setImage( RegisterMaterial( "hud_horizontal_compass_white" ) )
	f2_local1:setRGB( f2_arg0.colorR, f2_arg0.colorG, f2_arg0.colorB )
	f2_local1:setShaderVector( 0, 1, -0.5, 0, 0 )
	f2_local1:setupHorizontalCompass()
	f2_arg0:addElement( f2_local1 )
	if 0 == CoD.IS_KILLCAM_OR_SPECTATE( controller ) and 0 == UIExpression.IsDemoPlaying( controller ) then
		local f2_local2 = CoD.SplitscreenScaler.new( nil, CoD.SplitscreenMultiplier )
		f2_local2:setLeftRight( true, false, 0, 0 )
		f2_local2:setTopBottom( false, true, 0, 0 )
		f2_arg0.safeAreaContainer:addElement( f2_local2 )
		local f2_local3 = LUI.UIText.new()
		f2_local3:setLeftRight( true, false, 2, 3 )
		f2_local3:setTopBottom( false, true, -10 - CoD.textSize.Default, -10 )
		f2_local3:setText( Engine.Localize( "MP_REMOTE_EXIT" ) )
		f2_local3:setRGB( f2_arg0.colorR, f2_arg0.colorG, f2_arg0.colorB )
		f2_local3:setFont( CoD.fonts.Default )
		f2_local2:addElement( f2_local3 )
		local f2_local4 = LUI.UIText.new()
		f2_local4:setLeftRight( true, false, 0, 1 )
		f2_local4:setTopBottom( false, true, -40 - CoD.textSize.Default, -40 )
		f2_local4:setText( Engine.Localize( "KILLSTREAK_INCREASE_ZOOM" ) )
		f2_local4:setRGB( f2_arg0.colorR, f2_arg0.colorG, f2_arg0.colorB )
		f2_local4:setFont( CoD.fonts.Default )
		f2_local2:addElement( f2_local4 )
		local f2_local5 = LUI.UIText.new()
		f2_local5:setLeftRight( true, false, 0, 1 )
		f2_local5:setTopBottom( false, true, -70 - CoD.textSize.Default, -70 )
		f2_local5:setText( Engine.Localize( "MP_REAPER_FIRE_MISSILES" ) )
		f2_local5:setRGB( f2_arg0.colorR, f2_arg0.colorG, f2_arg0.colorB )
		f2_local5:setFont( CoD.fonts.Default )
		f2_local2:addElement( f2_local5 )
	end
end

