CoD.TurretHUD = {}
LUI.createMenu.turret = function ( f1_arg0 )
	local f1_local0 = CoD.AirVehicleHUD.new( "turret", f1_arg0 )
	f1_local0:addCompass()
	local self = LUI.UIImage.new()
	self:setLeftRight( false, false, -256, 256 )
	self:setTopBottom( false, false, -256, 256 )
	self:setImage( RegisterMaterial( "mp_hud_sentry_inner" ) )
	f1_local0:addElement( self )
	local f1_local2 = RegisterMaterial( "mp_hud_sentry_outer_white" )
	local f1_local3 = 512
	local f1_local4 = 256
	local f1_local5 = 80
	local f1_local6 = 20
	local f1_local7 = LUI.UIImage.new()
	f1_local7:setLeftRight( false, false, f1_local5, f1_local5 + f1_local3 )
	f1_local7:setTopBottom( false, false, f1_local6, f1_local6 + f1_local4 )
	f1_local7:setImage( f1_local2 )
	f1_local7:setRGB( f1_local0.colorR, f1_local0.colorG, f1_local0.colorB )
	f1_local0:addElement( f1_local7 )
	local f1_local8 = LUI.UIImage.new()
	f1_local8:setLeftRight( false, false, -f1_local5, -f1_local5 - f1_local3 )
	f1_local8:setTopBottom( false, false, f1_local6, f1_local6 + f1_local4 )
	f1_local8:setImage( f1_local2 )
	f1_local8:setRGB( f1_local0.colorR, f1_local0.colorG, f1_local0.colorB )
	f1_local0:addElement( f1_local8 )
	local f1_local9 = LUI.UIImage.new()
	f1_local9:setLeftRight( false, false, f1_local5, f1_local5 + f1_local3 )
	f1_local9:setTopBottom( false, false, -f1_local6, -f1_local6 - f1_local4 )
	f1_local9:setImage( f1_local2 )
	f1_local9:setRGB( f1_local0.colorR, f1_local0.colorG, f1_local0.colorB )
	f1_local0:addElement( f1_local9 )
	local f1_local10 = LUI.UIImage.new()
	f1_local10:setLeftRight( false, false, -f1_local5, -f1_local5 - f1_local3 )
	f1_local10:setTopBottom( false, false, -f1_local6, -f1_local6 - f1_local4 )
	f1_local10:setImage( f1_local2 )
	f1_local10:setRGB( f1_local0.colorR, f1_local0.colorG, f1_local0.colorB )
	f1_local0:addElement( f1_local10 )
	if CoD.IS_KILLCAM_OR_SPECTATE( f1_arg0 ) == 0 and UIExpression.IsDemoPlaying( f1_arg0 ) == 0 then
		local f1_local11 = LUI.UIText.new()
		f1_local11:setLeftRight( true, false, 0, 0 )
		f1_local11:setTopBottom( false, true, -30 - CoD.textSize.Default, -30 )
		f1_local11:setText( Engine.Localize( "MP_REMOTE_EXIT" ) )
		f1_local11:setFont( CoD.fonts.Default )
		f1_local11:setRGB( f1_local0.colorR, f1_local0.colorG, f1_local0.colorB )
		f1_local0.leftButtonPrompts:addElement( f1_local11 )
		local f1_local12 = LUI.UIText.new()
		f1_local12:setLeftRight( true, false, 0, 0 )
		f1_local12:setTopBottom( false, true, -CoD.textSize.Default, 0 )
		f1_local12:setText( Engine.Localize( "KILLSTREAK_INCREASE_ZOOM" ) )
		f1_local12:setFont( CoD.fonts.Default )
		f1_local12:setRGB( f1_local0.colorR, f1_local0.colorG, f1_local0.colorB )
		f1_local0.leftButtonPrompts:addElement( f1_local12 )
		local f1_local13 = LUI.UIText.new()
		f1_local13:setLeftRight( false, true, -1000, 0 )
		f1_local13:setTopBottom( false, true, -CoD.textSize.Default, 0 )
		f1_local13:setText( Engine.Localize( "MP_FIRE_SENTRY_GUN" ) )
		f1_local13:setFont( CoD.fonts.Default )
		f1_local13:setAlignment( LUI.Alignment.Right )
		f1_local13:setRGB( f1_local0.colorR, f1_local0.colorG, f1_local0.colorB )
		f1_local0.rightButtonPrompts:addElement( f1_local13 )
	end
	return f1_local0
end

